### ISSUE TITLE
Missing utils folder

### ISSUE THREAD

**Issue by dfenth** [RingBDStack/HAWK#1]
Hi there,
Thanks for providing the code for HAWK, it looks really interesting approach to malware classification and I'm hoping to invsetigate it further as part of a paper. It seems like a `utils` folder may be missing from the repo? On line 4 of `train.py` you reference `utils` and `process` which gives access to the `adj_to_bias` function which the script won't run without.

I was hoping this could be provided.

Thanks!

**Comment by heiyiming** [comment]
we have updated the code. Thanks.
